version: '3.9'
services:
  xui:
    image: unknownusernametopick/m-ui
    container_name: m-ui
    volumes:
      - $PWD/db/:/etc/m-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
